name: Gerar APK Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.0"
          channel: stable
          cache: true

      - name: Verificar Flutter
        run: flutter --version

      - name: Instalar dependencias
        run: flutter pub get

      - name: Gerar icones
        run: dart run flutter_launcher_icons

      - name: Gerar APK
        run: flutter build apk --debug

      - name: Salvar APK
        uses: actions/upload-artifact@v4
        with:
          name: Boleto-PDF-Android
          path: build/app/outputs/flutter-apk/app-debug.apk
